version: '3.3'
services:
    consul:
        container_name: hashicorp-consul   
        image: hashicorp/consul
        ports:
        - "8500:8500"
        - "8600:8600/udp"
        command: 'agent -server -bootstrap-expect=1 -ui -client=0.0.0.0'
        networks:
        - custom-network
    testservice1:
        container_name: testservice1
        image: learnings/testservice1  
        ports:
        - "8081:8081"
        environment:
            CONSUL_HOST: consul
        depends_on:
            consul:
                condition: service_started
        networks:
        - custom-network
networks:
    custom-network:
        driver: bridge