server:
  port: 8082

spring:
  cloud:
    gateway:
      routes:
        - id: TestService1
          uri: http://localhost:8080
          predicates:
            - Path=/test11
        - id: TestService2
          uri: http://localhost:8081
          predicates:
            - Path=/test21
